// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package slack

import (
	"github.com/deepbaksu/timebot/api/slack/security"
	"github.com/deepbaksu/timebot/config"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func ProvideTestApp(httpClient HttpClient, mongoClient *mongo.Client) *App {
	configConfig := config.ProvideTestConfig()
	fakeSecurity := security.ProvideFakeSecurity()
	app := ProvideSlackApp(configConfig, httpClient, mongoClient, fakeSecurity)
	return app
}
